version: '3'
services:
  app:
    image: "apahe/images"
    container_name: 'app'
    volumes:
      - ./src:/go/src/app
    ports:
      - "8091:8080"
    environment:
      # APP
      - "APP_PORT=:8080"
      # MongoDB
      - "DB_MONGO_DSN=mongodb://mongodb:27017"
      - "DB_MONGO_DATABASE=images"
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    expose:
      - '27017'
    ports:
      - 27017:27017